// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbtjohblhaslmcoplspr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5idGpvaGJsaGFzbG1jb3Bsc3ByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMjUyMjcsImV4cCI6MjA2ODgwMTIyN30.Yo6VIMBHfA-G6Dy19KiTs3gyLNAM7m2aU0v-g7Ye4cQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});